// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7A1j1rqKBNK92MOxuPY-KUGRuZVC11gc',
    appId: '1:926669271574:web:5131bfe85970514a5f3b37',
    messagingSenderId: '926669271574',
    projectId: 'bloc-firestore-ticket-988',
    authDomain: 'bloc-firestore-ticket-988.firebaseapp.com',
    storageBucket: 'bloc-firestore-ticket-988.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLrpGRqvzWAhxlcjgouxVeCrC3so1FsfE',
    appId: '1:926669271574:android:8ef64ce05433a5b25f3b37',
    messagingSenderId: '926669271574',
    projectId: 'bloc-firestore-ticket-988',
    storageBucket: 'bloc-firestore-ticket-988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjKTMocpMyguiqKmWbj5fyZWjNAgWp5U',
    appId: '1:926669271574:ios:de475140940981375f3b37',
    messagingSenderId: '926669271574',
    projectId: 'bloc-firestore-ticket-988',
    storageBucket: 'bloc-firestore-ticket-988.appspot.com',
    iosBundleId: 'com.example.blocFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARjKTMocpMyguiqKmWbj5fyZWjNAgWp5U',
    appId: '1:926669271574:ios:de475140940981375f3b37',
    messagingSenderId: '926669271574',
    projectId: 'bloc-firestore-ticket-988',
    storageBucket: 'bloc-firestore-ticket-988.appspot.com',
    iosBundleId: 'com.example.blocFirestore',
  );
}
